### ISSUE TITLE
(zod-openapi) - invalid JWT tokens throw `500 Server Error` instead of gracefully invalidating

### ISSUE THREAD

**Issue by callumfrance** [honojs/middleware#188]
Following on from https://github.com/honojs/middleware/issues/187, I have a separate issue specifically for managing JWTs in Zod OpenAPI Hono.

Taking the following JWT code in Hono -
```ts
import { Hono } from "hono";
import { jwt } from "hono/jwt";

const happ = new Hono();

happ.use("/fizz", jwt({ secret: "a-secret" }));

happ.get("/fizz", (c) => {
    const payload = c.get("jwtPayload");
    return c.json(payload);
});

export default happ;
```

The following request succeeds with `200` as it should:
```bash
curl --request GET \
  --url http://localhost:3000/fizz \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlIjoiaGVsbG8gd29ybGQifQ.B54pAqIiLbu170tGQ1rY06Twv__0qSHTA0ioQPIOvFE'
```
And this request with an invalid Bearer token gives `401` as it should:
```bash
curl --request GET \
  --url http://localhost:3000/fizz \
  --header 'Authorization: Bearer imbad'
  ```
  
  ---
  
Converting this code into Zod OpenAPI Hono like so -

```ts
import { OpenAPIHono } from "@hono/zod-openapi";
import { jwt } from "hono/jwt";

const app = new OpenAPIHono();

app.use("/fizz", jwt({ secret: "a-secret" }));

app.get("/fizz", (c) => {
    const payload = c.get("jwtPayload");
    return c.json(payload);
});

export default app;
```

When I run the valid request, I do in fact get the `200` response which is working as expected.

However, when I run an invalid request, instead of the `401`, I receive a `500` internal server error of the following:

```
  <-- GET /fizz
1 | // src/http-exception.ts
2 | var HTTPException = class extends Error {
3 |   constructor(status = 500, options) {
4 |     super(options?.message);
        ^
error: Error
      at new HTTPException (/Users/callum/Equator/borealis/node_modules/hono/dist/http-exception.js:4:4)
      at /Users/callum/Equator/borealis/node_modules/hono/dist/middleware/jwt/index.js:55:12
      at processTicksAndRejections (:55:76)

      at errorHandler (/Users/callum/Equator/borealis/node_modules/@hono/zod-openapi/node_modules/hono/dist/hono-base.js:19:2)
      at /Users/callum/Equator/borealis/node_modules/@hono/zod-openapi/node_modules/hono/dist/compose.js:58:32
      at /Users/callum/Equator/borealis/node_modules/@hono/zod-openapi/node_modules/hono/dist/compose.js:55:32
      at processTicksAndRejections (:55:76)
  --> GET /fizz 500 2ms
```

So I am left wondering what has happened in Zod OpenAPI Hono that has caused this server error to appear?

If it is relevant, I am using [bun](https://bun.sh/)

**Comment by yusukebe** [comment]
Hi @callumfrance 

Thanks for raising an issue, but I can't reproduce that behavior. It works well on my environment. Could you try it again? My dependencies are below:

```js
"dependencies": {
  "@hono/zod-openapi": "^0.7.2",
  "hono": "^3.7.2",
  "zod": "^3.22.4"
},
```

**Comment by callumfrance** [comment]
Ah, I am not sure why this was the case, but in my repo I had 
`"@hono/zod-openapi": "^0.4.0",` which is quite a bit older. I am pretty sure that updating this fixed the issue...
