### ISSUE TITLE
Auth.js middleware error

### ISSUE THREAD

**Issue by Fnux8890** [honojs/middleware#415]
hey I'm trying to get a hono server with auth js running. I found a package and guide in the repo so I tried it.
Unfortunately I'm getting the following error. I'm not sure if it something in the middleware or in the Auth.js packages

```bash
node:internal/modules/esm/resolve:303
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/bruger/Documents/Github/Semester_project_trustworthy/hub_server/node_modules/@auth/core/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:593:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at l.default._resolveFilename (/Users/bruger/Documents/Github/Semester_project_trustworthy/hub_server/node_modules/tsx/dist/cjs/index.cjs:1:1671)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at <anonymous> (/Users/bruger/Documents/Github/Semester_project_trustworthy/hub_server/node_modules/@hono/auth-js/dist/index.js:29:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I'm running node.js 20 and so also use the 
```js
import { serve } from "@hono/node-server";
```
This how ever worked before, so I assume that its not this package that screws things up.

thanks in advance

**Comment by yusukebe** [comment]
@Fnux8890 

Add `"type": "module"` to your `package.json`:

```json
{
  "type": "module",
```
