### ISSUE TITLE
@hono/sentry ESM support

### ISSUE THREAD

**Issue by thiskevinwang** [honojs/middleware#495]
## Problem 

When using `@hono/sentry` along with the newer `cloudflare:test` / [Vitest integration](https://developers.cloudflare.com/workers/testing/vitest-integration/), I get an error:

```console
Error: `require()` is not yet implemented in Workers.
Attempted to `require("toucan-js")` from "file:///[REDACTED]/node_modules/@hono/sentry/dist/index.js"
    at [REDACTED]/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/node/module.mjs:8:20
    at /[REDACTED]/node_modules/@hono/sentry/dist/index.js:4:21
    at VitestExecutor.runModule ([REDACTED]/node_modules/vite-node/dist/client.mjs:362:11)
    at VitestExecutor.runModule ([REDACTED]/node_modules/vitest/dist/vendor/execute.aFSzc0Da.js:549:20)
    at VitestExecutor.directRequest ([REDACTED]/node_modules/vite-node/dist/client.mjs:346:16)
    at VitestExecutor.cachedRequest ([REDACTED]/node_modules/vite-node/dist/client.mjs:189:14)
    at VitestExecutor.dependencyRequest ([REDACTED]/node_modules/vite-node/dist/client.mjs:233:12)
    at /[REDACTED]/src/middleware/sentry.ts:1:154
    at VitestExecutor.runModule ([REDACTED]/node_modules/vite-node/dist/client.mjs:362:5)
    at VitestExecutor.directRequest ([REDACTED]/node_modules/vite-node/dist/client.mjs:346:5)
 ❯ [REDACTED]/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/node/module.mjs:8:20
 ❯ node_modules/@hono/sentry/dist/index.js:4:21
      2| Object.defineProperty(exports, "__esModule", { value: true });
      3| exports.getSentry = exports.sentry = void 0;
      4| const toucan_js_1 = require("toucan-js");
       |                     ^
      5| class MockContext {
      6|     passThroughOnException() {
 ❯ src/middleware/sentry.ts:1:154
 ❯ [REDACTED]/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/node/module.mjs:9:11
 ❯ node_modules/@hono/sentry/dist/index.js:4:21
 ❯ src/middleware/sentry.ts:1:154
```

Here are some notable dependecies:
```jsonc
// package.json; (trimmed)
  "dependencies": {
    "@hono/sentry": "^1.0.1",
    "hono": "^4.0.1",
  },
  "devDependencies": {
    "@cloudflare/vitest-pool-workers": "https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/8850920915/npm-package-cloudflare-vitest-pool-workers-5508",
    "@vitest/coverage-v8": "1.3.0",
    "@vitest/ui": "1.3.0",
    "vite-tsconfig-paths": "^4.3.1",
    "vitest": "1.3.0",
    "wrangler": "https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/prs/5508/npm-package-wrangler-5508"
  }
```

## Proposed solution

Update `@hono/sentry` with ESM support.

I believe there was a similar issue with `@hono/zod-openapi`: https://github.com/honojs/middleware/issues/436. Linking some related work in [`asteasolutions/zod-to-openapi`](https://github.com/asteasolutions/zod-to-openapi/commit/732f52b4cbc3f7d0df661626bfed394e5faaee42#diff-47407fecafdf5f5cd55403c3de457833ddf9b6fab45253c04e1dc4c7cb4495b1)

For `@hono/sentry` and I think `toucan-js` already supports ESM[^1], so this might be an easy fix? 🤞  
[^1]:https://github.com/robertcepa/toucan-js/blob/master/packages/toucan-js/package.json#L7-L8

**Comment by thiskevinwang** [comment]
Aside, and for anyone curious, my current workaround is to alias `@hono/sentry` to a local "mock".

```ts
// vitest.config.ts
import path from 'node:path';
import tsconfigPaths from 'vite-tsconfig-paths';
import { defineWorkersConfig } from '@cloudflare/vitest-pool-workers/config';

export default defineWorkersConfig({
  resolve: {
    alias: {
      // Note: No relative paths allowed here
      '@hono/sentry': path.join(__dirname, './test/mock-sentry.ts'),
    },
  },
```

and

```ts
// ./test/mock-sentry.ts
import { vi } from 'vitest';

export const getSentry = vi.fn(() => {
  return {
    setTag: () => {},
    captureException: () => {},
  };
});

export const sentry = vi.fn(() => {
  // @ts-ignore
  return (c, next) => {
    return next();
  };
});
```

**Comment by yusukebe** [comment]
Hi @thiskevinwang 

I've released `v1.1.0` now. This may be fixed.

**Comment by thiskevinwang** [comment]
@yusukebe That was fast! I will try this out soon and report back. Thank you again!

**Comment by thiskevinwang** [comment]
@yusukebe `v1.1.0` works as expected, and [my workaround](https://github.com/honojs/middleware/issues/495#issuecomment-2093721330) is no longer needed! Thank you again ❤️
