### ISSUE TITLE
Type error in Context when using zod-openapi and swagger-ui

### ISSUE THREAD

**Issue by andyjp** [honojs/middleware#650]
Using [this example](https://github.com/honojs/middleware/tree/main/packages/swagger-ui#with-openapihono-usage) from the swagger-ui docs on usage with zod-openapi and deno version 1.44.4, I get the below error when running tests.

```
~/test-zod-openapi-swagger deno test
Check file:///Users/user/test-zod-openapi-swagger/index.test.ts
error: TS2769 [ERROR]: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env>' is not assignable to parameter of type 'H<Env, "/ui", BlankInput, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env>' is not assignable to type 'MiddlewareHandler<Env, "/ui", BlankInput>'.
        Types of parameters 'c' and 'c' are incompatible.
          Type 'Context<Env, "/ui", BlankInput>' is not assignable to type 'Context<Env, string, {}>'.
            Property '#private' in type 'Context' refers to a different member that cannot be accessed from within type 'Context'.
  swaggerUI({
  ^
    at file:///Users/user/test-zod-openapi-swagger/index.ts:36:3

TS2771 [ERROR]:     The last overload is declared here.
        at https://esm.sh/v135/hono@4.5.0/dist/types/types.d.ts:162:5
```

Here are files I used to duplicate the issue:

```typescript
// index.ts
import {
  createRoute,
  OpenAPIHono,
  z,
} from "https://esm.sh/@hono/zod-openapi@0.15.0";
import { swaggerUI } from "https://esm.sh/@hono/swagger-ui@0.4.0";

const app = new OpenAPIHono();

app.openapi(
  createRoute({
    method: "get",
    path: "/hello",
    responses: {
      200: {
        description: "Respond a message",
        content: {
          "application/json": {
            schema: z.object({
              message: z.string(),
            }),
          },
        },
      },
    },
  }),
  (c) => {
    return c.json({
      message: "hello",
    });
  },
);

app.get("/ui", swaggerUI({ url: "/doc" }));

app.doc("/doc", {
  info: {
    title: "An API",
    version: "v1",
  },
  openapi: "3.1.0",
});

export { app };
```

```typescript
// index.test.ts
import { app } from "./index.ts";

const res = await app.request("/hello");
console.log(await res.json());
```

**Comment by yusukebe** [comment]
Hi @andyjp 

This is caused by the fact that both packages don't refer to the same `hono` package:

![CleanShot 2024-07-19 at 07 33 42@2x](https://github.com/user-attachments/assets/b499be3b-eee2-4b1e-8872-39d35acdcec9)
![CleanShot 2024-07-19 at 07 33 55@2x](https://github.com/user-attachments/assets/c4eb4ae7-eb77-4591-9db0-e6b335904283)

They must refer to the same `hono` package. This means the same version in this case. This is not an actual bug of Hono matter but `esm.sh` matter. There may be a solution, but I can't imagine it now.

**Comment by andyjp** [comment]
Got it. I'll see if I can use versions of the packages that refer to the same hono package.
