### ISSUE TITLE
[`@hono/zod-openapi`]: `defaultHook` `result.error` type mismatch

### ISSUE THREAD

**Issue by Hugos68** [honojs/middleware#776]
The `result.error` parameter in the `defaultHook` callback is typed as `ZodError`, but when console.logging the `result.error` the shape is completely different:
```ts
// ZodError.d.ts
export declare class ZodError<T = any> extends Error {
    issues: ZodIssue[];
    get errors(): ZodIssue[];
    constructor(issues: ZodIssue[]);
    format(): ZodFormattedError<T>;
    format<U>(mapper: (issue: ZodIssue) => U): ZodFormattedError<T, U>;
    static create: (issues: ZodIssue[]) => ZodError<any>;
    static assert(value: unknown): asserts value is ZodError;
    toString(): string;
    get message(): string;
    get isEmpty(): boolean;
    addIssue: (sub: ZodIssue) => void;
    addIssues: (subs?: ZodIssue[]) => void;
    flatten(): typeToFlattenedError<T>;
    flatten<U>(mapper?: (issue: ZodIssue) => U): typeToFlattenedError<T, U>;
    get formErrors(): typeToFlattenedError<T, string>;
}
```

```txt
// Output `console.log(result.error)`
{
  "issues": [
    {
      "validation": "uuid",
      "code": "invalid_string",
      "message": "Invalid uuid",
      "path": [
        "id"
      ]
    }
  ],
  "name": "ZodError"
}
```

The same goes for the `result.target` object, it feels like the types don't all align properly.

**Comment by yusukebe** [comment]
Hi @Hugos68 

It seems to work fine:

```ts
import { OpenAPIHono, createRoute } from '@hono/zod-openapi'
import { z, ZodError } from 'zod'

const route = createRoute({
  method: 'get',
  path: '/',
  request: {
    query: z.object({
      q: z.string().openapi({ example: 'foo' })
    })
  },
  responses: {
    200: {
      description: 'hi'
    }
  }
})

const app = new OpenAPIHono({
  defaultHook: (result, c) => {
    if (result.success === false) {
      console.log(result.error instanceof ZodError) // true
      console.log(result.error)
    }
  }
})

app.openapi(route, (c) => {
  return c.text('Hi')
})

export default app
```

Output:

```
true
ZodError
    at get error (file:///Users/yusuke/work/h/my-app/node_modules/zod/lib/index.mjs:587:31)
    at null.<anonymous> (file:///Users/yusuke/work/h/my-app/node_modules/@hono/zod-openapi/node_modules/@hono/zod-validator/dist/esm/index.js:7:57)
    at null.<anonymous> (async file:///Users/yusuke/work/h/my-app/.wrangler/tmp/dev-fcI9To/zod-openapi.js:2517:17)
    at async dispatch (file:///Users/yusuke/work/h/my-app/node_modules/hono/dist/compose.js:29:17)
    at null.<anonymous> (async file:///Users/yusuke/work/h/my-app/.wrangler/tmp/dev-fcI9To/zod-openapi.js:3257:26)
    at async jsonError (file:///Users/yusuke/.config/yarn/global/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///Users/yusuke/.config/yarn/global/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}
```

**Comment by Hugos68** [comment]
Hmm, do you maybe know why I'm missing stuff like message, issues, etc in my result.error?

**Comment by yusukebe** [comment]
> Hmm, do you maybe know why I'm missing stuff like message, issues, etc in my result.error?

Hmm. I don't know, but you can confirm the `result.error` is an instance of `ZodError` or not.

**Comment by Hugos68** [comment]
@yusukebe I can indeed confirm that is the case, so I'll close this issue, thanks for all the help. I probably am doing something wrong myself to produce such a bare ZodError.
